version: '2.1'

services:
  cv:
    image: kikr/cv:latest
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 80:80
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 server.js